---
apiVersion: v1
kind: ConfigMap
metadata:
  name: books-api-v2-config
data:
  quarkus.otel.exporter.otlp.endpoint: http://otel-collector.observability.svc:4317
---
# Generate a ServiceMonitor resource for the books-api-v2 service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: books-api-v2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: books-api-v2
      app.kubernetes.io/version: 1.0.0 
  endpoints:
    - scheme: http
      targetPort: 9876
      path: /observe/metrics
      interval: 10s
      honorLabels: true