openapi: 3.0.2
info:
    title: Library Books API (v2)
    version: 2.0.0
    description: Manages a library books inventory
servers:
    -
        url: 'http://localhost:8080/api/v2'
        description: Server URL
paths:
    /books:
        summary: Path used to manage the list of books-v2.
        description: >-
            The REST endpoint/path used to list and create zero or more `books-v2` entities.  This path
            contains a `GET` operation to perform the list tasks.
        get:
            tags:
                - Books
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/book-v2'
                            examples:
                                ListOfBooks-v2:
                                    value:
                                        -
                                            author:
                                                birthDate: '1797-08-30T00:00:00.000Z'
                                                name: Mary Shelley
                                            copies: 10
                                            title: Frankenstein
                                            year: 1818
                                        -
                                            author:
                                                birthDate: '1812-02-07T00:00:00.000Z'
                                                name: Charles Dickens
                                            copies: 5
                                            title: A Christmas Carol
                                            year: 1843
                                        -
                                            author:
                                                birthDate: '1775-12-16T00:00:00.000Z'
                                                name: Charles Dickens
                                            copies: 3
                                            title: Pride and Prejudice
                                            year: 1813
                    description: Successful response - returns an array of `Books-v2` entities.
                '500':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                            examples:
                                error_500:
                                    value:
                                        error:
                                            id: '500'
                                            description: Internal Server Error
                                            messages:
                                                - 'java.lang.Exception: Mocked error message'
                    description: Internal Server Error
            operationId: getBooks-v2
            summary: List all books (v2) from the inventory
            description: Gets a list of all `book-v2` entities from the inventory.
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/book-v2'
                        examples:
                            NewBook-v2:
                                value:
                                    author:
                                        birthDate: '1642-12-25T00:00:00.000Z'
                                        name: Sir Isaac Newton
                                    copies: 31
                                    title: Philosophiæ Naturalis Principia Mathematica
                                    year: 1687
                required: true
            tags:
                - Books
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/book-v2'
                            examples:
                                NewListOfBooks-v2:
                                    value:
                                        -
                                            author:
                                                birthDate: '1797-08-30T00:00:00.000Z'
                                                name: Mary Shelley
                                            copies: 10
                                            title: Frankenstein
                                            year: 1818
                                        -
                                            author:
                                                birthDate: '1812-02-07T00:00:00.000Z'
                                                name: Charles Dickens
                                            copies: 5
                                            title: A Christmas Carol
                                            year: 1843
                                        -
                                            author:
                                                birthDate: '1775-12-16T00:00:00.000Z'
                                                name: Jane Austen
                                            copies: 3
                                            title: Pride and Prejudice
                                            year: 1813
                                        -
                                            author:
                                                birthDate: '1642-12-25T00:00:00.000Z'
                                                name: Sir Isaac Newton
                                            copies: 31
                                            title: Philosophiæ Naturalis Principia Mathematica
                                            year: 1687
                    description: Created
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                            examples:
                                validationResult_400:
                                    value:
                                        error:
                                            id: '400'
                                            description: Bad Request
                                            messages:
                                                - >-
                                                    JSON validation error with 2 errors:

                                                    $: required property 'author' not found

                                                    $: property 'authorName' is not defined in the schema and
                                                    the schema does not allow additional properties.
                                                    Exchange[94595332629B781-0000000000000002]
                    description: '`Membership`JSON data not valid'
                '500':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                            examples:
                                error_500:
                                    value:
                                        error:
                                            id: '500'
                                            description: Internal Server Error
                                            messages:
                                                - 'java.lang.Exception: Mocked error message'
                    description: Internal server error
            operationId: addNewBook-v2
            description: Adds a new `book-v2` entity in the inventory.
components:
    schemas:
        book-v2:
            title: Root Type for book-v2
            description: A Book (v2) entity
            required:
                - author
                - copies
                - title
                - year
            type: object
            properties:
                author:
                    required:
                        - birthDate
                        - name
                    type: object
                    properties:
                        birthDate:
                            format: date-time
                            type: string
                        name:
                            type: string
                    additionalProperties: false
                copies:
                    format: int32
                    type: integer
                title:
                    type: string
                year:
                    format: int32
                    type: integer
            additionalProperties: false
            example:
                author:
                    birthDate: '1797-08-30T00:00:00.000Z'
                    name: Mary Shelley
                copies: 10
                title: Frankenstein
                year: 1818
        Error:
            description: Error message structure
            type: object
            properties:
                error:
                    type: object
                    properties:
                        id:
                            type: string
                        description:
                            type: string
                        messages:
                            type: array
                            items:
                                type: object
            example:
                error:
                    id: '500'
                    description: Internal Server Error
                    messages:
                        - 'java.lang.Exception: Mocked error message'
tags:
    -
        name: Books
        description: ''
